#!/bin/bash
############################################################
# 
############################################################

function lock {
    i3lock --ignore-empty-password --show-failed-attempts -e -i $HOME/.config/i3/i3scripts/pictures/Dark_Iron_Man_1366x768.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    poweroff)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|poweroff}"
        exit 2
esac

exit 0
