#!/bin/bash
SCRIPT_DIR=$(dirname "$0")
while true; do
	find $SCRIPT_DIR/pictures -type f \( -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' \) -print0 |
    shuf -n1 -z | xargs -0 feh --bg-scale
    sleep 15m
done

